name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: mstksg/setup-stack@v2
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'
    - name: Install GHC
      run: stack setup
    - name: Build
      run: stack build
    - name: Run tests
      run: stack test
